parserOptions:
  ecmaVersion: latest
  sourceType: 'module'

env:
  es2017: true
  browser: true

extends: 'htmlacademy/vanilla'

rules:
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - { before: false, after: true }
  object-curly-spacing:
    - error
    - always
